### PR TITLE
Proto static html

### PR DESCRIPTION
**Pull request by armengau**
Operational version for demo
- Can use functions as library in notebooks
- Scripts to produce static html are still "raw" python scripts

I'm actually surprised by the small number of conflicts (3, and they're minor)
Probably due to the fact that, although I edited heavily the code, I didn't "break" its structure and just commented lines of code that really had to be removed.

### CODE REVIEW

**Comment by weaverba137** [comment]
@sbailey, @armengau, what is the current status of prospect?  I'm doing a demo of some spectrum visualization tools at NOAO next week, and I'd like to know what's going on with the various branches, which are considerably ahead of master.

**Comment by weaverba137** [comment]
So it looks like `hackday` is actually a branch off of `proto_static_html` not `master`.  @sbailey, could you please comment?

**Comment by sbailey** [comment]
Apologies for the radio silence.  Following the CMX/SV review we are reviving prospect development and visual inspection preparations.

"hackday" was a branch of off "proto_static_html" where I was attempting to re-organize the code into our typical desihub repo structure and get it into a state where it could be used by others without custom tweaks to their environment.  I got it far enough that people could use the spectral viewer in jupyter for the collab meeting hack day, but I didn't restructure the pieces for pre-generating the static HTML pages.

At this point we might be able to revive the hackday refactor to merge back into proto_static_html before merging into master, or we may just start over with the repo structure organization.

**Comment by weaverba137** [comment]
@armengau, your responses to questions on this PR are not being recorded.  Please use the GitHub page to respond to questions here so they can be archived.

Also, Is there a particular reason why work needs to continue on a branch of a branch of a branch?

Finally, could you please define "arborescence"?

**Comment by armengau** [comment]
Sorry I write again my previous email for record:

I have created the "svdc2019" branch from the last github version of "hackday", so merging directly svdc2019 into master should also be ok. I'm currently working on svdc2019 exclusively.

=> indeed no reason to continue to stay on this branch of branch... so I fully agree to merge it now on master


I'm trying to use the "tiles" *arborescence (not an english word..)* ==> tree view (?) in svdc2019c spectra :
=> this is the "tiles" subdir of /global/project/projectdirs/desi/datachallenge/svdc-summer2019/svdc2019c/spectro/redux/v1

- does it make sense ? ie will this structure be kept for SV? it's great to make static html pages on a nightly basis.
( - are there already eg. desispec.io routines to access this arborescence ? )
- I'm having an issue with the corresponding night-based "zbest" files : their 'SPECTYPE' and 'SUBTYPE' seem much more detailled than those we have when loading redrock templates, so that within the spectral viewer create_model() cannot work.

**Comment by weaverba137** [comment]
@armengau, I'm going to go ahead and close this PR, so that you can open a new PR and merge the `svdc2019` branch into master as soon as possible.  Please make sure that `svdc2019` is still working in your example notebook, commit any final changes, open a new PR, and merge that.

**Comment by weaverba137** [comment]
PS, please include a copy of your notebook when you merge the `svdc2019` branch.  The standard place for that is the `doc/nb` directory.

**Pull request closed without merging**
